#add_subdirectory(kernels/cuda)
list(APPEND objects
    biggrid_info.cpp
    big_grid.cpp
    divide_info.cpp
    gint_atom.cpp
    gint_info.cpp
    gint.cpp
    gint_vl.cpp
    gint_vl_nspin4.cpp
    localcell_info.cpp
    phi_operator.cpp
    unitcell_info.cpp
    gint_common.cpp
    gint_interface.cpp
    )
add_library(
    gint
    OBJECT
    ${objects}
)
