add_library(
    base
    OBJECT
    module_external/blas_connector_base.cpp
    module_external/blas_connector_vector.cpp
    module_external/blas_connector_matrix.cpp
    complexarray.cpp
    complexmatrix.cpp
    element_basis_index.cpp
    global_file.cpp
    global_function.cpp
    global_function_ddotreal.cpp
    global_variable.cpp
    intarray.cpp
    math_integral.cpp
    math_polyint.cpp
    math_sphbes.cpp
    math_ylmreal.cpp
    math_bspline.cpp
    mathzone_add1.cpp
    matrix.cpp
    matrix3.cpp
    memory_recorder.cpp
    mymath.cpp
    output.cpp
    realarray.cpp
    sph_bessel_recursive-d1.cpp
    sph_bessel_recursive-d2.cpp
    timer.cpp
    tool_check.cpp
    tool_quit.cpp
    tool_title.cpp
    ylm.cpp
    parallel_common.cpp
    parallel_global.cpp
    parallel_comm.cpp
    parallel_reduce.cpp
    parallel_device.cpp
    spherical_bessel_transformer.cpp
    cubic_spline.cpp
    parallel_2d.cpp
)

target_link_libraries(base PUBLIC container)
add_subdirectory(module_container)
